import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../globals.css";
import Sidebar from "../components/sidebar.jsx";
import Header from "../components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="d-flex">
          <Sidebar />

          
            <main className="flex-1 bg-gray-50" style={{ flexGrow: 1 }}>
                          <Header />

              <div className="flex flex-1" >

              {children}
                      </div>

            </main>
          </div>
      </body>
    </html>
  );
}
