import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../globals.css";
import Sidebar from "../components/sidebar.jsx";
import Header from "../components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Overall layout */}
        <div className="d-flex">
          <Sidebar />
          <div className="flex flex-1 custom-flex">
            
            <Header />
            {/* Main content area */}
            <main className="flex-1 p-6 bg-gray-50">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
