import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "../globals.css";
import "../responsive2.css";
import Sidebar2 from "../components/sidebar2.jsx";
import Sidebar from "../components/sidebar.jsx";
import Header from "../components/header";
import SideBarContextProvider from "@/context/sideBarContextProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en" style={{ scrollBehavior: "auto" }}>
      <body cz-shortcut-listen="true">

        <SideBarContextProvider>

          <div className="d-flex" style={{
            height:"100vh"
          }}>
            <Sidebar />
            <main className="flex-1 bg-gray-50" style={{ flexGrow: 1 }}>
              <Header />
              <div className="flex flex-1" >
                {children}
              </div>
            </main>
          </div>

        </SideBarContextProvider>


      </body>
    </html>
  );
}
